//
//  SampleData2.swift
//  momhood
//
//  Created by laptop on 2019-06-28.
//  Copyright © 2019 Langara. All rights reserved.
//

import Foundation

let json = """
[
{ "_id" : { "$oid" : "5d16ef2f6ab86f30f46adf40" }, "week_count" : 15, "period" : "2nd trimester", "baby" : { "name" : "Baby", "tagline" : "Baby Is Looking More Like A Baby", "fruitsize" : "an Avocado", "size" : "10 cm", "weight" : "71 g", "articles" : [ { "title" : "What do babies develop this week", "list" : [ "Generates hair folicles and hair color", "Skin remains super thin", "Blood vessels are developing", "Skeleton would be visible", "Ears are properly positioned on the sides of the head" ] } ] }, "yourbody" : { "tagline" : "Heartburn & Indigestion", "articles" : [ { "title" : "Symptoms", "imageurl" : "xxxx", "list" : [ "Heartburn & indigestion", "Faintness or dizziness", "Occasional headache", "Forgetfulness" ] }, { "title" : "Body Changes", "imageurl" : "xxxx", "list" : [ "Lung capacity increases", "Rib cage enlarges up to around 3 inches", "Swollen bloow vessels in your legs" ] } ] }, "diet" : { "tagline" : "Breakfast is Priority", "articles" : [ { "title" : "What to Eat", "imageurl" : "xxxx", "list" : [ "Almond is a great source for preventing heartburn and indigestion", "Get plenty of vitamin-C rich food", "Get your omega-3s on: DHA rich-food (salmon, walnuts, tofu, leafly green veggetables", "Banana and orange juice are great source of potassium before exercising" ] }, { "title" : "What to Limit", "imageurl" : "xxxx", "list" : [ "Undercook meat, poultry and eggs to avoid foodborne illness", "Limit refined carbohydrate food source: white rice, white bread, sweets , soda ,etc.", "Limit processed food comsumption and start to go with fresh ones" ] } ] }, "activities" : { "tagline" : "Think of a baby name list", "articles" : [ { "title" : "Lifestyle", "imageurl" : "xxxx", "list" : [ "Get pregnancy pillows and start sleeping on your left", "Try gently exercising your legs, ankles and feet", "Always have breakfast" ] }, { "title" : "Recommendation", "imageurl" : "xxxx", "list" : [ "Schedule you multiple marker screening", "Schecule your amniocentesis", "Start carrying a small notebook", "Think of a baby name list" ] } ] } },
{ "_id" : { "$oid" : "5d16fac96ab86f30f46adf65" }, "week_count" : 14, "period" : "2nd trimester", "baby" : { "name" : "Baby", "tagline" : "", "fruitsize" : "a Pear", "size" : "0", "weight" : "0", "articles" : [  ] }, "yourbody" : { "tagline" : "", "articles" : [  ] }, "diet" : { "tagline" : "", "articles" : [  ] }, "activities" : { "tagline" : "", "articles" : [  ] } },
{ "_id" : { "$oid" : "5d16fabb6ab86f30f46adf64" }, "week_count" : 13, "period" : "2nd trimester", "baby" : { "name" : "Baby", "tagline" : "", "fruitsize" : "a Peach", "size" : "0", "weight" : "0", "articles" : [  ] }, "yourbody" : { "tagline" : "", "articles" : [  ] }, "diet" : { "tagline" : "", "articles" : [  ] }, "activities" : { "tagline" : "", "articles" : [  ] } },
{ "_id" : { "$oid" : "5d16fa9d6ab86f30f46adf63" }, "week_count" : 11, "period" : "1st trimester", "baby" : { "name" : "Baby", "tagline" : "", "fruitsize" : "a Strawberry", "size" : "0", "weight" : "0", "articles" : [  ] }, "yourbody" : { "tagline" : "", "articles" : [  ] }, "diet" : { "tagline" : "", "articles" : [  ] }, "activities" : { "tagline" : "", "articles" : [  ] } },
{ "_id" : { "$oid" : "5d16fa026ab86f30f46adf62" }, "week_count" : 10, "period" : "1st trimester", "baby" : { "name" : "Baby", "tagline" : "", "fruitsize" : "a Fig", "size" : "0", "weight" : "0", "articles" : [  ] }, "yourbody" : { "tagline" : "", "articles" : [  ] }, "diet" : { "tagline" : "", "articles" : [  ] }, "activities" : { "tagline" : "", "articles" : [  ] } },
{ "_id" : { "$oid" : "5d16f9f56ab86f30f46adf61" }, "week_count" : 9, "period" : "1st trimester", "baby" : { "name" : "Baby", "tagline" : "", "fruitsize" : "a Green Olive", "size" : "0", "weight" : "0", "articles" : [  ] }, "yourbody" : { "tagline" : "", "articles" : [  ] }, "diet" : { "tagline" : "", "articles" : [  ] }, "activities" : { "tagline" : "", "articles" : [  ] } },
{ "_id" : { "$oid" : "5d16f9e56ab86f30f46adf60" }, "week_count" : 8, "period" : "1st trimester", "baby" : { "name" : "Baby", "tagline" : "", "fruitsize" : "a Grape", "size" : "0", "weight" : "0", "articles" : [  ] }, "yourbody" : { "tagline" : "", "articles" : [  ] }, "diet" : { "tagline" : "", "articles" : [  ] }, "activities" : { "tagline" : "", "articles" : [  ] } },
{ "_id" : { "$oid" : "5d16f9756ab86f30f46adf5f" }, "week_count" : 7, "period" : "1st trimester", "baby" : { "name" : "Baby", "tagline" : "", "fruitsize" : "a Raspberry", "size" : "0", "weight" : "0", "articles" : [  ] }, "yourbody" : { "tagline" : "", "articles" : [  ] }, "diet" : { "tagline" : "", "articles" : [  ] }, "activities" : { "tagline" : "", "articles" : [  ] } },
{ "_id" : { "$oid" : "5d16f95d6ab86f30f46adf5e" }, "week_count" : 6, "period" : "1st trimester", "baby" : { "name" : "Baby", "tagline" : "", "fruitsize" : "a Blueberry", "size" : "0", "weight" : "0", "articles" : [  ] }, "yourbody" : { "tagline" : "", "articles" : [  ] }, "diet" : { "tagline" : "", "articles" : [  ] }, "activities" : { "tagline" : "", "articles" : [  ] } },
{ "_id" : { "$oid" : "5d16f9326ab86f30f46adf5d" }, "week_count" : 5, "period" : "1st trimester", "baby" : { "name" : "Baby", "tagline" : "", "fruitsize" : "a Grain of Rice", "size" : "0", "weight" : "0", "articles" : [  ] }, "yourbody" : { "tagline" : "", "articles" : [  ] }, "diet" : { "tagline" : "", "articles" : [  ] }, "activities" : { "tagline" : "", "articles" : [  ] } },
{ "_id" : { "$oid" : "5d16f9246ab86f30f46adf5c" }, "week_count" : 4, "period" : "1st trimester", "baby" : { "name" : "Baby", "tagline" : "", "fruitsize" : "a Sesame Seed", "size" : "0", "weight" : "0", "articles" : [  ] }, "yourbody" : { "tagline" : "", "articles" : [  ] }, "diet" : { "tagline" : "", "articles" : [  ] }, "activities" : { "tagline" : "", "articles" : [  ] } },
{ "_id" : { "$oid" : "5d16f9176ab86f30f46adf5b" }, "week_count" : 3, "period" : "1st trimester", "baby" : { "name" : "Baby", "tagline" : "", "fruitsize" : "a Vanilla Bean Seed", "size" : "0", "weight" : "0", "articles" : [  ] }, "yourbody" : { "tagline" : "", "articles" : [  ] }, "diet" : { "tagline" : "", "articles" : [  ] }, "activities" : { "tagline" : "", "articles" : [  ] } },
{ "_id" : { "$oid" : "5d16f9026ab86f30f46adf5a" }, "week_count" : 2, "period" : "1st trimester", "baby" : { "name" : "Baby", "tagline" : "", "fruitsize" : "a Poppy Seed", "size" : "0", "weight" : "0", "articles" : [  ] }, "yourbody" : { "tagline" : "", "articles" : [  ] }, "diet" : { "tagline" : "", "articles" : [  ] }, "activities" : { "tagline" : "", "articles" : [  ] } },
{ "_id" : { "$oid" : "5d16f8ec6ab86f30f46adf59" }, "week_count" : 1, "period" : "1st trimester", "baby" : { "name" : "Baby", "tagline" : "", "fruitsize" : "a Cell", "size" : "0", "weight" : "0", "articles" : [  ] }, "yourbody" : { "tagline" : "", "articles" : [  ] }, "diet" : { "tagline" : "", "articles" : [  ] }, "activities" : { "tagline" : "", "articles" : [  ] } },
]
""".data(using: .utf8)!

public func retrieveSampleData() -> Data {
    return json
}

let jsonCurrentWeek = """
{ "_id" : { "$oid" : "5d16f0e76ab86f30f46adf48" }, "week_count" : 16, "period" : "2nd semester", "baby" : { "name" : "Baby", "tagline" : "Baby's First Hiccups Ahead!", "fruitsize" : "a Navel Orange", "size" : "10 - 13 cm", "weight" : "0.09 - 0.11 kg", "articles" : [ { "title" : "What do babyes develop this week", "list" : [ "Baby is listening to your voice", "Baby is growing hair, lashes and eyebrows", "The taste buds are forming", "Thumb sucking habit already begun", "The ciculatory system is now up and running" ] } ] }, "yourbody" : { "tagline" : "Heartburn & Indigestion", "articles" : [ { "title" : "Symptoms", "imageurl" : "xxxx", "list" : [ "Occasional headache", "Faintness or dizziness", "Heartburn & indigestion", "Backaches", "Sciatica nerve pain", "Periodontitis", "Skin pigmentation" ] }, { "title" : "Body Changes", "imageurl" : "xxxx", "list" : [ "Your breast continue growing", "Increased vaginal discharge, may cause discomfort", "Swollen bloow vessels in your legs" ] } ] }, "diet" : { "tagline" : "Breakfast is Priority", "articles" : [ { "title" : "What to Eat", "imageurl" : "xxxx", "list" : [ "Keep your weight gain healthy and gradual", "Get enough food sources for vitamin C to produce collagen and elastin", "Go for greens and lentils", "Get your iron on!", "Drink enough liquid", "Increase in whole grains, fruits, vegetables, low-fat nutrient-rich proteins, unsaturated fats" ] }, { "title" : "What to Limit", "imageurl" : "xxxx", "list" : [ "Limit your caffein intake. If you're coffee lover, have half of a cup daily", "Decrease in saturated and trans fats , sweetened beverages and other refined sugars", "Avoid bisque and cream soups", "Don't go with big meals as it may cause constipation", "If you're seafood lover, start avoid seafood that high in mercury" ] } ] }, "activities" : { "tagline" : "Think of a baby name list", "articles" : [ { "title" : "Lifestyle", "imageurl" : "xxxx", "list" : [ "Try a prenatal message to lower your backaches", "Take warm baths or showers", "Take care of your dental health (floss more and visit your dentist)", "Replace any fluids you lose after 30 minutes sweating excercise" ] }, { "title" : "Recommendation", "imageurl" : "xxxx", "list" : [ "Schedule your prenatal visit", "Schedule your mid-preganacy ultrasound", "Schedule for the Quad screen", "Avoid sleeping on your back", "Talk to your baby", "Keep your weight gain healthy and gradual" ] } ] } }
""".data(using: .utf8)!

public func retrieveCurrentWeek() -> Data {
    return jsonCurrentWeek
}
